[package]
name = "rvc-rs-audio"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[features]
default = []
cpal-backend = ["dep:cpal"]

[dependencies]
cpal = { workspace = true, optional = true }
hound.workspace = true
thiserror.workspace = true

[lib]
path = "src/lib.rs"
