[package]
name = "rvc-rs-inference"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[features]
default = []
cuda = ["rvc-rs-engine/cuda"]
metal = ["rvc-rs-engine/metal"]

[dependencies]
eframe.workspace = true
rfd.workspace = true
rvc-rs-core.workspace = true
rvc-rs-engine.workspace = true
serde.workspace = true

[[bin]]
name = "rvc-rs-inference"
path = "src/main.rs"
